# Generated by Django 5.0.1 on 2024-01-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='skin_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
