# Generated by Django 5.0.1 on 2024-04-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_weapon_description_alter_weapon_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='exterior',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='weapon',
            name='float',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='skin_type',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
