# Generated by Django 5.0.1 on 2024-04-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_weapon_inventory_rename_skin_name_weapon_weapon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
